name: Android CI

on:
  push:
    branches:  
        - develop 
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Write permission for Gradlew
      run: cmod +x ./gradlew
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'adopt'
        cache: gradle

    - name: Build App
      run: ./gradlew buildDebug
